Fixing bugs with groundwater, irrigation, canopy and root development
aquacropos/aquacrop pull request #162
Opened 2024-06-24 13:43 UTC by oleksmialyk

I was comparing AquaCrop-OSPy based on AquaCrop v6.1 (2022) vs v7.0 (2024) and found several bugs including:

1. check_groundwater_table.py doesn't return NewCond_zGW variable leading to constant groundwater levels (see #99)
2. HIref_current_day.py doesn't check for NewCond_CC_prev <= (Crop.CCmin*Crop.CCx) condition as it used to do in AquaCrop-OSPy v6.1 (perhaps it's how new AquaCrop v7 works, please confirm)
3. irrigation.py has hardcoded 15mm irrigation for IrrMngt_IrrMethod == 1 (see #132)
4. root_development.py doesn't return NewCond_rCor which is supposed to be updated daily according to AquaCrop-OSPy v6.1

2024-07-15 15:38 UTC, chris-s-bowden requested changes
The changes to run_single_timestep make sense and will be approved.

The changes to infiltration are incorrect, because the zBund is supplied in metres so should be converted to millimetres (*1000) during these calculations. Please either remove these changes or provide evidence to support the removal of the '*1000' before resubmitting this commit.

2024-07-15 15:52 UTC, chris-s-bowden requested changes
First of all, thank you for spotting a number of discrepancies in the code! Here are our comments:

In HIref_current_day, we purposefully made and tested the removal of L106-108 in this commit as part of the update from v6 to v7. Please remove this change before resubmitting.

The return of zGW in check_groundwater_table is correct and will be accepted.

The removal of hard-coded value in irrigation is correct and will be accepted.

The return of rCor in root_development is correct and will be accepted.

In run_single_timestep, all changes are correct apart from L273 which you have already fixed in the subsequent bunds-related commit.

2024-08-06 12:20 UTC, oleksmialyk commented
> The changes to run_single_timestep make sense and will be approved.
> 
> The changes to infiltration are incorrect, because the zBund is supplied in metres so should be converted to millimetres (*1000) during these calculations. Please either remove these changes or provide evidence to support the removal of the '*1000' before resubmitting this commit.

Thanks :)
zBund in m would be fine if its use was consistent through the code. In some cases, it's compared to other variables in mm which leads to a mismatch in units. E.g:
- _FieldMngtTmp.z_bund_ in read_model_initial_conditions.py
- _FieldMngt.z_bund_ in reset_initial_conditions.py

Since the whole water balance is done in mm, we can make it consistent with zBund too so the users are less confused. Also, it's a bit strange that zBund is in m but bund_water (initial storage) in mm. Alternatively, you can search through all instances of zBund and z_bund to make sure it's everywhere multiplied by 1000. But again, this adds unnecessary operations to the code.

> First of all, thank you for spotting a number of discrepancies in the code! Here are our comments:
> 
> In HIref_current_day, we purposefully made and tested the removal of L106-108 in this commit as part of the update from v6 to v7. Please remove this change before resubmitting.
> 
> The return of zGW in check_groundwater_table is correct and will be accepted.
> 
> The removal of hard-coded value in irrigation is correct and will be accepted.
> 
> The return of rCor in root_development is correct and will be accepted.
> 
> In run_single_timestep, all changes are correct apart from L273 which you have already fixed in the subsequent bunds-related commit.

I removed lines in HIref_current_day, thanks.

2024-08-14 09:38 UTC, chris-s-bowden approved these changes

2024-08-14 09:58 UTC, merged